controle_acesso/acesso/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('visitantes/', views.visitantes, name='visitantes'),
  path('novo-visitante/', views.novo_visitante, name='novo_visitante'),
  path('visitante/<int:visitante_id>/', views.visitante, name='visitante'),
  path('visitante/editar/<int:visitante_id>/', views.editar_visitante, name='editar_visitante'),

  path('registrar-acesso/', views.registrar_acesso, name='registrar_acesso'),
  path('finalizar-acesso/<int:acesso_id>/', views.finalizar_acesso, name='finalizar_acesso'),

  path("contas/", include("django.contrib.auth.urls")),
]

controle_acesso/controle_acesso/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('acesso.urls')),
]

controle_acesso/acesso/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

class Pessoa(models.Model):
  SEXO_CHOICES = (
    ('M', 'Masculino'),
    ('F', 'Feminino')
  )
  nome = models.CharField(max_length=256, blank=False, null=False)
  cpf = models.CharField(max_length=11, blank=False, null=False)
  telefone = models.CharField(max_length=11, blank=True, null=True)
  genero = models.CharField(max_length=1, choices=SEXO_CHOICES, blank=False, null=False)
  data_nascimento = models.DateField(blank=False, null=False)

  def __str__(self):
    return self.nome
  
class Funcionario(Pessoa):
  TURNO_CHOICES = (
    ('M', 'Manhã'),
    ('T', 'Tarde'),
    ('N', 'Noite'),
  )

  matricula = models.CharField(max_length=5, blank=False, null=False)
  cargo = models.CharField(max_length=256, blank=False, null=False)
  turno = models.CharField(max_length=1, choices=TURNO_CHOICES, blank=False, null=False)
  usuario = models.OneToOneField(User, related_name= 'funcionario', on_delete=models.CASCADE)

  def nome_completo(self):
    return self.usuario.username + " " + self.usuario.last_name

class Visitante(Pessoa):
  TIPO_CHOICES = (
    ('E', 'Escola'),
    ('D', 'Delivery'),
    ('V', 'Visita técnica'),
  )

  tipo = models.CharField(max_length=1, choices=TIPO_CHOICES, blank=False, null=False)

class Endereco(models.Model):
  logradouro = models.CharField(max_length=256, blank=False, null=False)
  numero = models.CharField(max_length=8, blank=True, null=True)
  bairro = models.CharField(max_length=256, blank=False, null=False)
  cidade = models.CharField(max_length=256, blank=False, null=False)
  estado = models.CharField(max_length=256, blank=False, null=False)
  cep = models.CharField(max_length=8, blank=False, null=False)
  pessoa = models.ForeignKey(Pessoa, blank=False, null=False, on_delete=models.CASCADE, related_name='enderecos')

class Veiculo(models.Model):
  placa = models.CharField(max_length=12, blank=False, null=False)
  modelo = models.CharField(max_length=64, blank=False, null=False)
  ano = models.IntegerField(null=False, blank=False)
  cor = models.CharField(max_length=64, blank=False, null=False)
  pessoa = models.ForeignKey(Pessoa, blank=False, null=False, on_delete=models.CASCADE, related_name='veiculos')

  def __str__(self):
    return self.placa + " de " + self.pessoa.nome

class RegistroAcesso(models.Model):
  STATUS_CHOICES = (
    ('E', 'Em andamento'),
    ('F', 'Finalizado'),
  )
  pessoa = models.ForeignKey(Pessoa, blank=False, null=False, on_delete=models.CASCADE)
  veiculo = models.ForeignKey(Veiculo, blank=True, null=True, on_delete=models.CASCADE)
  data_hora_entrada = models.DateTimeField(blank=False, null=False)
  data_hora_saida = models.DateTimeField(blank=True, null=True)
  status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='E', blank=False, null=False)

  def atualiza_status(self):
    self.status = 'F'
    self.atualiza_hora_saida(datetime.now())
    self.save()

  def atualiza_hora_saida(self, hora_saida):
    self.data_hora_saida = hora_saida
    self.save()

controle_acesso/acesso/forms.py
from django import forms
from .models import Visitante, Veiculo, Endereco, Pessoa, RegistroAcesso
from django.forms.models import inlineformset_factory

class PessoaForm(forms.ModelForm):

  class Meta:
    model = Pessoa
    fields = '__all__'
    widgets = {
      'cpf': forms.NumberInput(
        attrs = {
          'class': 'form-control'
        }
      ),
      'telefone': forms.NumberInput(
        attrs = {
          'class': 'form-control'
        }
      ),
      'genero': forms.Select(
        attrs = {
          'class': 'form-control'
        }
      ),
      'data_nascimento': forms.DateInput(
        attrs = {
          'class': 'form-control'
        }
      ),
    }

class VisitanteForm(forms.ModelForm):

  class Meta:
    model = Visitante
    fields = '__all__'
    widgets = {
      'tipo': forms.Select(
        attrs = {
          'class': 'form-control'
        }
      ),
      'nome': forms.TextInput(
        attrs = {
          'class': 'form-control'
        }
      ),
      'cpf': forms.NumberInput(
        attrs = {
          'class': 'form-control'
        }
      ),
      'telefone': forms.NumberInput(
        attrs = {
          'class': 'form-control'
        }
      ),
      'genero': forms.Select(
        attrs = {
          'class': 'form-control'
        }
      ),
      'data_nascimento': forms.DateInput(
        attrs = {
          'class': 'form-control'
        }
      ),
    }

class VeiculoForm(forms.ModelForm):

  class Meta:
    model = Veiculo
    # fields = '__all__'
    exclude = ('pessoa',)
    widgets = {
      'placa': forms.TextInput(
        attrs= {
          'class': 'form-control'
        }
      ),
      'modelo': forms.TextInput(
        attrs= {
          'class': 'form-control'
        }
      ),
      'ano': forms.TextInput(
        attrs= {
          'class': 'form-control'
        }
      ),
      'cor': forms.TextInput(
        attrs= {
          'class': 'form-control'
        }
      ),
    }

class EnderecoForm(forms.ModelForm):

  class Meta:
    model = Endereco
    # fields = '__all__'
    exclude = ('pessoa',)
    widgets = {
      'logradouro': forms.TextInput(
        attrs= {
          'class': 'form-control'
        }
      ),
      'numero': forms.NumberInput(
        attrs= {
          'class': 'form-control'
        }
      ),
      'bairro': forms.TextInput(
        attrs= {
          'class': 'form-control'
        }
      ),
      'cidade': forms.TextInput(
        attrs= {
          'class': 'form-control'
        }
      ),
      'estado': forms.TextInput(
        attrs= {
          'class': 'form-control'
        }
      ),
      'cep': forms.NumberInput(
        attrs= {
          'class': 'form-control'
        }
      ),
      
    }

class RegistroAcessorForm(forms.ModelForm):
  class Meta:
    model = RegistroAcesso
    # fields = '__all__'
    exclude = ('status', 'data_hora_saida','data_hora_entrada')

    widgets = {
      'pessoa': forms.Select(
        attrs= {
          'class': 'form-control'
        }
      ),
      'veiculo': forms.Select(
        attrs= {
          'class': 'form-control'
        }
      ),
      'data_hora_entrada': forms.DateTimeInput(
        attrs= {
          'class': 'form-control'
        }
      ),
    }

controle_acesso/acesso/views.py
from django.shortcuts import render, redirect
from .models import RegistroAcesso, Visitante
from .forms import EnderecoForm, VeiculoForm, VisitanteForm, RegistroAcessorForm
from django.shortcuts import get_object_or_404
from datetime import datetime
from django.contrib.auth.decorators import login_required

@login_required(login_url="/contas/login/")
def index(request):
  acessos = RegistroAcesso.objects.all()
  context = { "acessos": acessos }
  return render(request, 'index.html', context)

@login_required(login_url="/contas/login/")
def visitantes(request):
  visitantes = Visitante.objects.all()
  context = { "visitantes": visitantes}
  return render(request, 'visitante/index.html', context)

@login_required(login_url="/contas/login/")
def novo_visitante(request):
  form_endereco = EnderecoForm()
  form_visitante = VisitanteForm()
  form_veiculo = VeiculoForm()

  if request.method == 'POST':
    form_endereco = EnderecoForm(request.POST)
    form_visitante = VisitanteForm(request.POST)
    form_veiculo = VeiculoForm(request.POST)
    
    if form_visitante.is_valid() and form_endereco.is_valid() and form_veiculo.is_valid:
      visitante = form_visitante.save()
      endereco = form_endereco.save(commit=False)
      veiculo = form_veiculo.save(commit=False)
      veiculo.pessoa = visitante
      veiculo.save()
      endereco.pessoa = visitante
      endereco.save()

  context = { "form_endereco": form_endereco, "form_visitante": form_visitante, "form_veiculo": form_veiculo}
  return render(request, 'visitante/new.html', context)

@login_required(login_url="/contas/login/")
def visitante(request, visitante_id):
  visitante = get_object_or_404(Visitante, id=visitante_id)
  context = { "visitante": visitante }
  return render(request, 'visitante/view.html', context)

@login_required(login_url="/contas/login/")
def editar_visitante(request, visitante_id):
  visitante = get_object_or_404(Visitante, id=visitante_id)
  form_visitante = VisitanteForm(instance=visitante)
  

  if request.method == 'POST':
    form_visitante = VisitanteForm(request.POST, instance=visitante)
  
    if form_visitante.is_valid():
      form_visitante.save()
      return redirect('visitante', visitante.id)

  context = { "visitante": visitante, "form_visitante": form_visitante }

  return render(request, 'visitante/edit.html', context)

@login_required(login_url="/contas/login/")
def registrar_acesso(request):
  form = RegistroAcessorForm()

  if request.method == 'POST':
    form = RegistroAcessorForm(request.POST)

    if form.is_valid():
      datetime.now()
      acesso = form.save(commit=False)
      acesso.data_hora_entrada = datetime.now()
      acesso.save()
      return redirect('index')
  
  context = { "form": form }

  return render(request, 'acesso/registrar.html', context)

@login_required(login_url="/contas/login/")
def finalizar_acesso(request, acesso_id):
  acesso = get_object_or_404(RegistroAcesso, id=acesso_id)
  acesso.atualiza_status()
  return redirect(index)

controle_acesso/acesso/templates/visitante/edit.html
{% extends "base.html" %}

{% block content %}
	<h2>Editar Visitante</h2>
  <form method="POST" enctype="multipart/form-data">
 
    <!-- Security token -->
    {% csrf_token %}
    
    
    <div class="card">
      <div class="card-body">
        <div class="card-title">
          <h3>Dados visitante</h3>
        </div>
        
        {% if form_visitante.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert"
            aria-hidden="true">
            </button>
            por favor, verifique erros
            {{ form_visitante.errors }}
          </div>
        {% endif %}
        {{form_visitante}}
      </div>
      <div class="card-footer">
        <input type="submit" value="Salvar" class="btn btn-sm btn-primary">
        <a href="{% url 'visitante' visitante.id %}" class="btn btn-sm btn-secondary">Voltar</a>
      </div>
    </div>
  </form>
{% endblock %}

controle_acesso/acesso/templates/visitante/index.html
{% extends "base.html" %}

{% block content %}
	<h2>Visitantes</h2>
  <a class="btn btn-sm btn-primary" href="{% url 'novo_visitante' %}">Novo visitante</a>

  <h3>Listagem de visitantes</h3>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Telefone</th>
        <th scope="col">Data nascimento</th>
        <th scope="col">Acão</th>
      </tr>
    </thead>
    <tbody>
      {% for visitante in visitantes %}
        <tr>
          <th scope="row">{{visitante.id}}</th>
          <td>{{ visitante.nome}}</td>
          <td>{{ visitante.telefone}}</td>
          <td>{{ visitante.data_nascimento}}</td>
          <td><a href="{% url 'visitante' visitante.id %}" class="btn btn-sm btn-secondary">Visualizar</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

controle_acesso/acesso/templates/visitante/new.html
{% extends "base.html" %}

{% block content %}
	<h2>Criar Visitante</h2>
  <form method="POST" enctype="multipart/form-data">
 
    <!-- Security token -->
    {% csrf_token %}
    
    
    <div class="card">
      <div class="card-body">
        <div class="card-title">
          <h3>Dados visitante</h3>
        </div>
        
        {% if form_visitante.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert"
            aria-hidden="true">
            </button>
            por favor, verifique erros
            {{ form_visitante.errors }}
          </div>
        {% endif %}
        {{form_visitante}}
      </div>
    </div>

    <div class="card">
      <div class="card-body">
        <div class="card-title">
          <h3>Dados endereco</h3>
        </div>
        {% if form_endereco.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert"
            aria-hidden="true">
            </button>
            por favor, verifique erros
            {{ form_endereco.errors }}
          </div>
        {% endif %}
        {{form_endereco}}

      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <div class="card-title">
          <h3>Dados Veículo</h3>
        </div>
        {% if form_veiculo.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert"
            aria-hidden="true">
            </button>
            por favor, verifique erros
            {{ form_veiculo.errors }}
          </div>
        {% endif %}
        {{form_veiculo}}
      </div>
      <div class="card-footer">
        <input type="submit" value="Salvar" class="btn btn-sm btn-primary">
        <a href="{% url 'index' %}" class="btn btn-sm btn-secondary">Voltar</a>
      </div>
    </div>
  </form>
{% endblock %}

controle_acesso/acesso/templates/visitante/view.html
{% extends "base.html" %}

{% block content %}
	<h2>Visitante</h2>

  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <div class="card-title">
            <h3>Dados do visitante</h3>
          </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><dt>Nome</dt><dd>{{visitante.nome}}</dd></li>
              <li class="list-group-item"><dt>cpf</dt><dd>{{visitante.cpf}}</dd></li>
              <li class="list-group-item"><dt>Telefone</dt><dd>{{visitante.telefone}}</dd></li>
              <li class="list-group-item"><dt>Genero</dt><dd>{{visitante.get_genero_display}}</dd></li>
              <li class="list-group-item"><dt>Data nascimento</dt><dd>{{visitante.data_nascimento}}</dd></li>
              <li class="list-group-item"><dt>Tipo</dt><dd>{{visitante.get_tipo_display}}</dd></li>
              <li class="list-group-item"><a href="{% url 'editar_visitante' visitante.id %}" class="btn btn-sm btn-primary">Editar</a></li>
            </ul>
        </div>
      </div>
    </div>
  
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <div class="card-title">
            <h3>Endereço</h3>
          </div>
            {% for endereco in visitante.enderecos.all %}  
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><dt>Logradouro</dt><dd>{{endereco.logradouro}}</dd></li>
                <li class="list-group-item"><dt>Numero</dt><dd>{{endereco.numero}}</dd></li>
                <li class="list-group-item"><dt>Bairro</dt><dd>{{endereco.bairro}}</dd></li>
                <li class="list-group-item"><dt>Cidade</dt><dd>{{endereco.cidade}} - {{endereco.estado}}</dd></li>
                <li class="list-group-item"><dt>Cep</dt><dd>{{endereco.cep}}</dd></li>
                <li class="list-group-item"><a href="#" class="btn btn-sm btn-primary">Editar</a></li>
              </ul>
            {%endfor%}
        </div>
      </div>
    </div>
  </div>
  
  <div class="row-fluid">
    <div class="card">
      <div class="card-body">
        <div class="card-title">
          <h3>Veículos</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Placa</th>
              <th scope="col">Cor</th>
              <th scope="col">modelo</th>
            </tr>
          </thead>
          <tbody>
            {% for veiculo in visitante.veiculos.all %}
              <tr>
                <th scope="row">{{veiculo.placa}}</th>
                <td>{{ veiculo.modelo}}</td>
                <td>{{ veiculo.cor}}</td>
                <td><a href="#" class="btn btn-sm btn-primary">Editar</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}